apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongodb
        ports:
        - containerPort: 27017
        name: mongodb
        env:
        - name: MONGO_INITDB_DATABASE
          value: "Bookstore"